name: "Build"
on:
  push:
    branches:
      - "main"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.reader.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - id: reader
        run: |
          # read versions.json and set it as an output
          echo "::set-output name=versions::$(cat versions.json)"

  build:
    runs-on: ubuntu-latest
    needs:
      - discover
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.discover.outputs.versions) }}
    name: "Build ${{ matrix.version }}"
    steps:
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - run: |
          echo "Hello from ${{ matrix.version }}"
          zig --version
