name: "Build"
on:
  push:
    branches:
      - "main"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.reader.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - id: reader
        run: |
          # read versions.json and set it as an output
          echo "::set-output name=versions::$(cat versions.json)"

  build:
    runs-on: ubuntu-latest
    needs:
      - discover
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.discover.outputs.versions) }}
    name: "Build ${{ matrix.version }}"
    steps:
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - name: "Install node-build"
        run: |
          git clone https://github.com/nodenv/node-build.git --depth 1
          PREFIX=/usr/local sudo ./node-build/install.sh
      - run: node-build --version
      - run: zig version
      - run: |
          CC="zig cc -target aarch64-macos-gnu" node-build --compile --verbose "${{ matrix.version }}" "./output"
      - run: ls output
